// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwdgdkghuldtokvmtsmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3ZGdka2dodWxkdG9rdm10c210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDU4NTAsImV4cCI6MjA2NDQyMTg1MH0.rECbZZUqET0ybpVyr_yF3HWYeIE8AJVvbfIdj4rJFW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);